### ISSUE TITLE
Errors in Drag to Reorder with Jetpack Compose 1.1.1

### ISSUE THREAD

**Issue by jeluchu** [Ahmed-Sellami/List-Animations-In-Compose#1]
First of all thank you for your work because there are very few places where you can find an interesting way to order the elements of a LazyColumn, I have been testing and I have detected errors that [I show you in this video](https://ibb.co/jGd7SqM)

When you have more elements it starts to generate a kind of blank spaces, and it seems that the element that moves, is placed above the element that is already in that position, having in the same position 2 different elements, so that the original position remains empty, and the new one has two elements

**Comment by Ahmed-Sellami** [comment]
Thanks for telling me about the issue. Actually, I was about to ensure that it wouldn't happen when I started this repository, and then, I forgot. It's fixed now.
