### ISSUE TITLE
Drag to reorder only on long click!

### ISSUE THREAD

**Issue by Monabr** [Ahmed-Sellami/List-Animations-In-Compose#2]
Please make such implementation:

1. Long click happened.
2. Item go to rotated state so it ready to reorder.
3. Reorder happens.

**Comment by Ahmed-Sellami** [comment]
Could you elaborate more? Isn't that what already happens?

**Comment by Monabr** [comment]
No. Now it's working using usual click

**Comment by Ahmed-Sellami** [comment]
I see what you mean now. I'll do it.

**Comment by Ahmed-Sellami** [comment]
After the last commit, Modifier.dragToReorder accepts a parameter called isDraggedAfterLongPress to tell the function whether you want the drag to trigger after a long press or not.
